services:
  - type: web
    name: weatherbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_PROJECT
        value: weatherbot
      - key: LANGCHAIN_ENDPOINT
        value: https://api.smith.langchain.com 